# Site Settings
baseurl: ""
url : "https://pariente1995.github.io"
timezone: Asia/Seoul

# Blog Settings
theme_settings :
  title : Spooner's Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.png
    username : SeHyeok Park
    description : 먹는 것과 맛집 탐방을 좋아하는 웹 개발자 준비생입니다. <br> 현재 AWS클라우드 기반 자바(JAVA) 웹개발 국비교육 과정 중에 있습니다.
                  <br><br><br> <p style="font-size:13px;">PS. 인스타그램을 통하여 맛집을 사람들과 공유 및 기록하고 있습니다.</p>
    experience :
      - start : 2020-01-01
        end : 2022-06-30
        experience : (주)영림원소프트랩 <p style="font-weight:500;font-size:13px;">ERP 프로세스 개발</p>
      - start : 2022-07-26
        end : 2023-01-10
        experience : AWS클라우드 기반 자바(JAVA) 웹개발<p style="font-weight:500;font-size:13px;">국비교육</p>
    skills : 
      - skill : JAVA
        value : 75  # Percent value
      - skill : HTML5 & CSS
        value : 75  # Percent value
      - skill : Javascript
        value : 60  # Percent value
      - skill : Database(ORACLE, MSSQL)
        value : 60  # Percent value
      - skill : JSP & Spring
        value : 50  # Percent value
        
  # Icons
  icons :
    email: pariente@naver.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: pariente1995
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: se_spoon

  # Disqus
  disqus_shortname : sehyeok-blog

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
