# Site Settings
baseurl: ""
url : "https://pariente1995.github.io"

# Blog Settings
theme_settings :
  title : SeHyeok's Portfolio
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : SeHyeok Park
    description : 안녕하세요 박세혁입니다.
    experience :
      - start : 2020-01-01
        end : 2022-06-30
        experience : (주)영림원소프트랩 <p style="font-weight:500;font-size:13px;">ERP 프로세스 개발</p>
      - start : 2022-07-26
        end : 2023-01-09
        experience : AWS클라우드 기반 자바(JAVA) 웹개발<p style="font-weight:500;font-size:13px;">국비교육</p>
    skills : 
      - skill : JAVA
        value : 75  # Percent value
      - skill : HTML5 & CSS
        value : 75  # Percent value
      - skill : Javascript
        value : 0  # Percent value
      - skill : Database(ORACLE, MSSQL)
        value : 70  # Percent value
      - skill : JSP & Spring
        value : 0  # Percent value
        
  # Icons
  icons :
    email: pariente@naver.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: pariente1995
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: se_spoon

  # Disqus
  disqus_shortname : sehyeok-blog

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
